<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CollegeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now()->toDateTimeString();
        DB::table('colleges')->insert(
            [
                "name" => "École française de Rome",
                "city" => "Rome",
                "code_postal" => 186,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École d'ingénieurs des sciences aérospatiales",
                "city" => "Saint-Quentin",
                "code_postal" => 2100,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Côte d'Azur",
                "city" => "Nice",
                "code_postal" => 6103,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Y SCHOOLS",
                "city" => "Troyes",
                "code_postal" => 10000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de technologie de Troyes",
                "city" => "Troyes",
                "code_postal" => 10004,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École française d'Athènes",
                "city" => "Athènes",
                "code_postal" => 10680,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut français d'archéologie orientale du Caire",
                "city" => "Le Caire",
                "code_postal" => 11441,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut supérieur du bâtiment et des travaux publics",
                "city" => "Marseille 13e",
                "code_postal" => 13006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Aix-Marseille Université",
                "city" => "Marseille 7e",
                "code_postal" => 13284,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Centrale Méditerranée",
                "city" => "Marseille 13e",
                "code_postal" => 13451,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Sciences Po Aix",
                "city" => "Aix-en-Provence",
                "code_postal" => 13625,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Ecole de l'air et de l'espace",
                "city" => "Salon-de-Provence",
                "code_postal" => 13661,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure d'arts et médias de Caen - Cherbourg",
                "city" => "Caen",
                "code_postal" => 14000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Caen Normandie",
                "city" => "Caen",
                "code_postal" => 14032,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'ingénieurs de Caen",
                "city" => "Caen",
                "code_postal" => 14050,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "BUILDERS École d'ingénieurs",
                "city" => "Épron",
                "code_postal" => 14610,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Excelia Group",
                "city" => "La Rochelle",
                "code_postal" => 17000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "La Rochelle Université",
                "city" => "La Rochelle",
                "code_postal" => 17031,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "EIGSI La Rochelle",
                "city" => "La Rochelle",
                "code_postal" => 17041,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national des sciences appliquées Centre Val de Loire",
                "city" => "Bourges",
                "code_postal" => 18022,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Corse Pasquale Paoli",
                "city" => "Corte",
                "code_postal" => 20250,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Burgundy School of Business",
                "city" => "Dijon",
                "code_postal" => 21006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Bourgogne",
                "city" => "Dijon",
                "code_postal" => 21078,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure de mécanique et des microtechniques",
                "city" => "Besançon",
                "code_postal" => 25030,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Franche-Comté",
                "city" => "Besançon",
                "code_postal" => 25030,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Casa de Velázquez de Madrid",
                "city" => "Madrid",
                "code_postal" => 28040,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut supérieur de l'électronique et du numérique de Brest",
                "city" => "Brest",
                "code_postal" => 29200,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École navale",
                "city" => "Lanvéoc",
                "code_postal" => 29200,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Brest Business School",
                "city" => "Brest",
                "code_postal" => 29238,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale d'ingénieurs de Brest",
                "city" => "Plouzané",
                "code_postal" => 29238,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Bretagne Occidentale",
                "city" => "Brest",
                "code_postal" => 29238,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure de techniques avancées Bretagne",
                "city" => "Brest",
                "code_postal" => 29806,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Nîmes",
                "city" => "Nîmes",
                "code_postal" => 30021,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Sciences Po Toulouse",
                "city" => "Toulouse",
                "code_postal" => 31000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Toulouse Capitole",
                "city" => "Toulouse",
                "code_postal" => 31000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Toulouse INP",
                "city" => "Toulouse",
                "code_postal" => 31029,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut supérieur de l'aéronautique et de l'espace",
                "city" => "Toulouse",
                "code_postal" => 31055,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale de l'aviation civile",
                "city" => "Toulouse",
                "code_postal" => 31055,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale de la météorologie",
                "city" => "Toulouse",
                "code_postal" => 31057,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Toulouse - Jean Jaurès",
                "city" => "Toulouse",
                "code_postal" => 31058,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Toulouse III - Paul Sabatier",
                "city" => "Toulouse",
                "code_postal" => 31062,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Toulouse Business School",
                "city" => "Toulouse",
                "code_postal" => 31068,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut catholique de Toulouse",
                "city" => "Toulouse",
                "code_postal" => 31068,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École d'ingénieurs de Purpan",
                "city" => "Toulouse",
                "code_postal" => 31076,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale vétérinaire de Toulouse",
                "city" => "Toulouse",
                "code_postal" => 31076,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national des sciences appliquées de Toulouse",
                "city" => "Toulouse",
                "code_postal" => 31077,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'architecture de Toulouse",
                "city" => "Toulouse",
                "code_postal" => 31106,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure de formation de l’enseignement agricole",
                "city" => "Castanet-Tolosan",
                "code_postal" => 31326,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure des sciences agronomiques de Bordeaux Aquitaine",
                "city" => "Gradignan",
                "code_postal" => 33175,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "KEDGE Business School",
                "city" => "Talence",
                "code_postal" => 33405,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Bordeaux INP",
                "city" => "Talence",
                "code_postal" => 33405,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Bordeaux",
                "city" => "Talence",
                "code_postal" => 33405,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Sciences Po Bordeaux",
                "city" => "Pessac",
                "code_postal" => 33607,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Bordeaux Montaigne",
                "city" => "Pessac",
                "code_postal" => 33607,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Montpellier",
                "city" => "Montpellier",
                "code_postal" => 34090,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "MBS",
                "city" => "Montpellier",
                "code_postal" => 34185,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paul-Valéry - Montpellier 3",
                "city" => "Montpellier",
                "code_postal" => 34199,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Rennes 2",
                "city" => "Rennes",
                "code_postal" => 35043,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Rennes School of Business",
                "city" => "Rennes",
                "code_postal" => 35065,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ECAM Rennes Louis de Broglie",
                "city" => "Bruz",
                "code_postal" => 35170,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut catholique de Rennes",
                "city" => "Bruz",
                "code_postal" => 35170,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Rennes",
                "city" => "Rennes",
                "code_postal" => 35700,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Tours",
                "city" => "Tours",
                "code_postal" => 37020,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Grenoble Alpes",
                "city" => "Saint-Martin-d'Hères",
                "code_postal" => 38400,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Jean Monnet",
                "city" => "Saint-Étienne",
                "code_postal" => 42023,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Nantes Université",
                "city" => "Nantes",
                "code_postal" => 44000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Audencia Business School",
                "city" => "Nantes",
                "code_postal" => 44105,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure du bois",
                "city" => "Nantes",
                "code_postal" => 44306,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale vétérinaire, agroalimentaire et de l'alimentation, Nantes-Atlantique",
                "city" => "Nantes",
                "code_postal" => 44307,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université d'Orléans",
                "city" => "Orléans",
                "code_postal" => 45067,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École d'ingénieur d'agro-développement international",
                "city" => "Angers",
                "code_postal" => 49000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure des sciences commerciales d'Angers",
                "city" => "Angers",
                "code_postal" => 49003,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure d’agriculture",
                "city" => "Angers",
                "code_postal" => 49007,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Facultés libres de l'Ouest",
                "city" => "Angers",
                "code_postal" => 49008,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université d'Angers",
                "city" => "Angers",
                "code_postal" => 49035,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure d'électronique de l'Ouest",
                "city" => "Angers",
                "code_postal" => 49107,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure angevine en informatique et productique",
                "city" => "Saint-Barthélemy-d'Anjou",
                "code_postal" => 49124,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut des relations publiques et de la communication d’Angers",
                "city" => "Les Ponts-de-Cé",
                "code_postal" => 49136,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Reims Champagne-Ardenne",
                "city" => "Reims",
                "code_postal" => 51724,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ICN Business School",
                "city" => "Nancy",
                "code_postal" => 54003,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Lorraine",
                "city" => "Nancy",
                "code_postal" => 54052,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Bretagne Sud",
                "city" => "Lorient",
                "code_postal" => 56321,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École spéciale militaire de Saint-Cyr",
                "city" => "Guer",
                "code_postal" => 56380,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure d'ingénieurs des travaux de la construction de Metz",
                "city" => "Metz",
                "code_postal" => 57070,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Hautes études d'ingénieur",
                "city" => "Lille",
                "code_postal" => 59014,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut catholique de Lille",
                "city" => "Lille",
                "code_postal" => 59016,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut supérieur d'agriculture de Lille",
                "city" => "Lille",
                "code_postal" => 59046,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Junia",
                "city" => "Lille",
                "code_postal" => 59046,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École des hautes études commerciales du nord",
                "city" => "Roubaix",
                "code_postal" => 59057,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Polytechnique Hauts-de-France",
                "city" => "Aulnoy-lez-Valenciennes",
                "code_postal" => 59313,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université du Littoral Côte d’Opale",
                "city" => "Dunkerque",
                "code_postal" => 59375,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Centrale Lille Institut",
                "city" => "Villeneuve-d'Ascq",
                "code_postal" => 59651,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Skema Business School",
                "city" => "Lille",
                "code_postal" => 59777,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Lille",
                "city" => "Lille",
                "code_postal" => 59800,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut d'économie scientifique et de gestion",
                "city" => "Lille",
                "code_postal" => 59800,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut polytechnique UniLaSalle",
                "city" => "Beauvais",
                "code_postal" => 60026,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure de chimie organique et minérale",
                "city" => "Compiègne",
                "code_postal" => 60200,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Technologie de Compiègne",
                "city" => "Compiègne",
                "code_postal" => 60203,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université d'Artois",
                "city" => "Arras",
                "code_postal" => 62030,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Clermont Auvergne",
                "city" => "Clermont-Ferrand",
                "code_postal" => 63001,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'architecture de Clermont-Ferrand",
                "city" => "Clermont-Ferrand",
                "code_postal" => 63100,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Pau et des Pays de l'Adour",
                "city" => "Pau",
                "code_postal" => 64012,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure des technologies industrielles avancées",
                "city" => "Bidart",
                "code_postal" => 64210,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de technologie Tarbes Occitanie Pyrénées",
                "city" => "Tarbes",
                "code_postal" => 65016,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Perpignan Via Domitia",
                "city" => "Perpignan",
                "code_postal" => 66860,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale du génie de l'eau et de l'environnement de Strasbourg",
                "city" => "Strasbourg",
                "code_postal" => 67000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national du service public",
                "city" => "Strasbourg",
                "code_postal" => 67000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'architecture de Strasbourg",
                "city" => "Strasbourg",
                "code_postal" => 67068,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Strasbourg",
                "city" => "Strasbourg",
                "code_postal" => 67081,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national des sciences appliquées de Strasbourg",
                "city" => "Strasbourg",
                "code_postal" => 67084,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Haute-Alsace",
                "city" => "Mulhouse",
                "code_postal" => 68093,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut catholique de Lyon",
                "city" => "Lyon 2e",
                "code_postal" => 69002,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Sciences Po Lyon",
                "city" => "Lyon 7e",
                "code_postal" => 69007,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Centrale Lyon",
                "city" => "Écully",
                "code_postal" => 69134,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut textile et chimique",
                "city" => "Écully",
                "code_postal" => 69134,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale des travaux publics de l'État",
                "city" => "Vaulx-en-Velin",
                "code_postal" => 69256,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Vet Agro Sup",
                "city" => "Marcy-l'Étoile",
                "code_postal" => 69280,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École catholique des arts et métiers",
                "city" => "Lyon 5e",
                "code_postal" => 69321,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure des arts et techniques du théâtre",
                "city" => "Lyon 5e",
                "code_postal" => 69322,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École normale supérieure de Lyon",
                "city" => "Lyon 7e",
                "code_postal" => 69342,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut supérieur d’agriculture Rhône-Alpes",
                "city" => "Lyon 7e",
                "code_postal" => 69364,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Lumière - Lyon 2",
                "city" => "Lyon 7e",
                "code_postal" => 69365,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Jean Moulin - Lyon 3",
                "city" => "Lyon 8e",
                "code_postal" => 69372,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure de chimie physique électronique de Lyon",
                "city" => "Villeurbanne",
                "code_postal" => 69616,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national des sciences appliquées de Lyon",
                "city" => "Villeurbanne",
                "code_postal" => 69621,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Claude Bernard - Lyon 1",
                "city" => "Villeurbanne",
                "code_postal" => 69622,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure des sciences de l'information et des bibliothèques",
                "city" => "Villeurbanne",
                "code_postal" => 69623,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ISMANS",
                "city" => "Le Mans",
                "code_postal" => 72000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Le Mans Université",
                "city" => "Le Mans",
                "code_postal" => 72085,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Savoie Mont Blanc",
                "city" => "Chambéry",
                "code_postal" => 73000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national d'histoire de l'art",
                "city" => "Paris 2e",
                "code_postal" => 75002,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national du patrimoine",
                "city" => "Paris 2e",
                "code_postal" => 75002,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure d'informatique électronique automatique",
                "city" => "Paris 5e",
                "code_postal" => 75005,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Muséum national d'histoire naturelle",
                "city" => "Paris 5e",
                "code_postal" => 75005,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "IAE Paris - Sorbonne Business School",
                "city" => "Paris 5e",
                "code_postal" => 75005,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paris-Panthéon-Assas",
                "city" => "Paris 5e",
                "code_postal" => 75005,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'architecture de Paris-Malaquais",
                "city" => "Paris 6e",
                "code_postal" => 75006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut supérieur d'électronique de Paris",
                "city" => "Paris 6e",
                "code_postal" => 75006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Sorbonne Université",
                "city" => "Paris 6e",
                "code_postal" => 75006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "IPAG Business School",
                "city" => "Paris 6e",
                "code_postal" => 75006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École des hautes études en sciences sociales",
                "city" => "Paris 6e",
                "code_postal" => 75006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paris sciences et lettres",
                "city" => "Paris 6e",
                "code_postal" => 75006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paris Cité",
                "city" => "Paris 6e",
                "code_postal" => 75006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Groupe Institut catholique d'arts et métiers",
                "city" => "Paris 9e",
                "code_postal" => 75009,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure de création industrielle - Les Ateliers",
                "city" => "Paris 8e",
                "code_postal" => 75011,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national du sport, de l'expertise et de la performance",
                "city" => "Paris 12e",
                "code_postal" => 75012,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Sorbonne Nouvelle - Paris 3",
                "city" => "Paris 12e",
                "code_postal" => 75012,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut français de la mode",
                "city" => "Paris 13e",
                "code_postal" => 75013,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Arts et Métiers Sciences et Technologies",
                "city" => "Paris 13e",
                "code_postal" => 75013,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École spéciale d'architecture",
                "city" => "Paris 14e",
                "code_postal" => 75014,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Facultés Libres de Philosophie et de Psychologie",
                "city" => "Paris 14e",
                "code_postal" => 75014,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut protestant de théologie",
                "city" => "Paris 14e",
                "code_postal" => 75014,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École centrale d'électronique",
                "city" => "Paris 15e",
                "code_postal" => 75015,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ESCP Business School",
                "city" => "Paris 15e",
                "code_postal" => 75015,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national d'enseignement supérieur pour l'agriculture, l'alimentation et l'environnement",
                "city" => "Paris 16e",
                "code_postal" => 75016,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'architecture de Paris-La Villette",
                "city" => "Paris 19e",
                "code_postal" => 75019,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'architecture de Paris-Belleville",
                "city" => "Paris 19e",
                "code_postal" => 75019,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École française d'Extrême-Orient",
                "city" => "Paris 16e",
                "code_postal" => 75116,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Conservatoire national des arts et métiers",
                "city" => "Paris 3e",
                "code_postal" => 75141,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national des langues et civilisations orientales",
                "city" => "Paris 13e",
                "code_postal" => 75214,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Collège de France",
                "city" => "Paris 5e",
                "code_postal" => 75231,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paris 1 - Panthéon Sorbonne",
                "city" => "Paris 5e",
                "code_postal" => 75231,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure des arts décoratifs",
                "city" => "Paris 5e",
                "code_postal" => 75240,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut catholique de Paris",
                "city" => "Paris 6e",
                "code_postal" => 75270,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Sciences Po",
                "city" => "Paris 7e",
                "code_postal" => 75337,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut supérieur du commerce de Paris",
                "city" => "Paris 17e",
                "code_postal" => 75848,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Le Havre Normandie",
                "city" => "Le Havre",
                "code_postal" => 76063,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Neoma Business School",
                "city" => "Mont-Saint-Aignan",
                "code_postal" => 76130,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'architecture de Normandie",
                "city" => "Darnétal",
                "code_postal" => 76161,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure maritime",
                "city" => "Le Havre",
                "code_postal" => 76600,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École de management de Normandie",
                "city" => "Le Havre",
                "code_postal" => 76600,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national des sciences appliquées de Rouen Normandie",
                "city" => "Saint-Étienne-du-Rouvray",
                "code_postal" => 76801,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure d'ingénieurs en génie électrique",
                "city" => "Saint-Étienne-du-Rouvray",
                "code_postal" => 76801,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Rouen Normandie",
                "city" => "Mont-Saint-Aignan",
                "code_postal" => 76821,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut européen d'administration des affaires",
                "city" => "Fontainebleau",
                "code_postal" => 77305,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Gustave Eiffel",
                "city" => "Champs-sur-Marne",
                "code_postal" => 77420,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale des sciences géographiques",
                "city" => "Champs-sur-Marne",
                "code_postal" => 77455,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale des ponts et chaussées",
                "city" => "Champs-sur-Marne",
                "code_postal" => 77455,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure de paysage",
                "city" => "Versailles",
                "code_postal" => 78000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d’architecture de Versailles",
                "city" => "Versailles",
                "code_postal" => 78006,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Versailles Saint-Quentin-en-Yvelines",
                "city" => "Versailles",
                "code_postal" => 78035,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure des techniques aéronautiques et de construction automobile",
                "city" => "Montigny-le-Bretonneux",
                "code_postal" => 78066,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École des hautes études commerciales de Paris",
                "city" => "Jouy-en-Josas",
                "code_postal" => 78351,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Picardie Jules-Verne",
                "city" => "Amiens",
                "code_postal" => 80025,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national universitaire Jean-François Champollion",
                "city" => "Albi",
                "code_postal" => 81012,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ISEN Yncréa Méditerranée",
                "city" => "Toulon",
                "code_postal" => 83000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Toulon",
                "city" => "La Garde",
                "code_postal" => 83041,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Avignon Université",
                "city" => "Avignon",
                "code_postal" => 84029,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut catholique de Vendée",
                "city" => "La Roche-sur-Yon",
                "code_postal" => 85017,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Poitiers",
                "city" => "Poitiers",
                "code_postal" => 86073,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure de mécanique et d'aérotechnique de Poitiers",
                "city" => "Chasseneuil-du-Poitou",
                "code_postal" => 86961,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut d'ingénierie informatique de Limoges",
                "city" => "Limoges",
                "code_postal" => 87015,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Limoges",
                "city" => "Limoges",
                "code_postal" => 87032,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure des technologies et des affaires de Belfort",
                "city" => "Belfort",
                "code_postal" => 90004,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de technologie de Belfort-Montbéliard",
                "city" => "Sevenans",
                "code_postal" => 90010,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université d'Évry-Val-d'Essonne",
                "city" => "Évry-Courcouronnes",
                "code_postal" => 91000,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure d'informatique pour l'industrie et l'entreprise",
                "city" => "Évry-Courcouronnes",
                "code_postal" => 91025,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut Mines-Télécom, au périmètre des écoles IMT Atlantique, Lille Douai, Albi, Alès, Mines Saint-Étienne et Institut Mines-Télécom Business school",
                "city" => "Palaiseau",
                "code_postal" => 91120,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut polytechnique de Paris",
                "city" => "Palaiseau",
                "code_postal" => 91128,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paris-Saclay",
                "city" => "Gif-sur-Yvette",
                "code_postal" => 91190,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national des sciences et techniques nucléaires",
                "city" => "Gif-sur-Yvette",
                "code_postal" => 91191,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paris Nanterre",
                "city" => "Nanterre",
                "code_postal" => 92001,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "CESI",
                "city" => "Puteaux",
                "code_postal" => 92074,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut national supérieur de formation et de recherche pour l'éducation inclusive",
                "city" => "Suresnes",
                "code_postal" => 92150,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure de fonderie et de forge",
                "city" => "Sèvres",
                "code_postal" => 92310,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure du pétrole et des moteurs",
                "city" => "Rueil-Malmaison",
                "code_postal" => 92852,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ESIEE Paris",
                "city" => "Noisy-le-Grand",
                "code_postal" => 93162,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure Louis Lumière",
                "city" => "Saint-Denis",
                "code_postal" => 93200,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paris 8 - Vincennes - Saint-Denis",
                "city" => "Saint-Denis",
                "code_postal" => 93200,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ISAE-Supméca",
                "city" => "Saint-Ouen-sur-Seine",
                "code_postal" => 93400,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Sorbonne Paris Nord",
                "city" => "Villetaneuse",
                "code_postal" => 93430,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université Paris-Est Créteil",
                "city" => "Créteil",
                "code_postal" => 94010,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut polytechnique des sciences avancées",
                "city" => "Ivry-sur-Seine",
                "code_postal" => 94200,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École spéciale de mécanique et d'électricité",
                "city" => "Ivry-sur-Seine",
                "code_postal" => 94200,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École spéciale des travaux publics, du bâtiment et de l'industrie",
                "city" => "Cachan",
                "code_postal" => 94230,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "EPF - École d'ingénieurs",
                "city" => "Cachan",
                "code_postal" => 94230,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure d'ingénieurs des travaux de la construction de Paris",
                "city" => "Arcueil",
                "code_postal" => 94234,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École pour l'informatique et les techniques avancées",
                "city" => "Le Kremlin-Bicêtre",
                "code_postal" => 94276,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale vétérinaire d'Alfort",
                "city" => "Maisons-Alfort",
                "code_postal" => 94700,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Institut Sup'Biotech de Paris",
                "city" => "Villejuif",
                "code_postal" => 94800,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "CY Cergy Paris Université",
                "city" => "Cergy",
                "code_postal" => 95011,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École nationale supérieure de l'électronique et de ses applications de Cergy",
                "city" => "Cergy",
                "code_postal" => 95014,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École supérieure des sciences économiques et commerciales",
                "city" => "Cergy",
                "code_postal" => 95021,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ECAM-EPMI",
                "city" => "Cergy",
                "code_postal" => 95092,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "École de biologie industrielle",
                "city" => "Cergy",
                "code_postal" => 95094,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "ESIEE-IT",
                "city" => "Pontoise",
                "code_postal" => 95300,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université des Antilles",
                "city" => "Pointe-à-Pitre",
                "code_postal" => 97157,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Guyane",
                "city" => "Cayenne",
                "code_postal" => 97337,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de Mayotte",
                "city" => "Dembeni",
                "code_postal" => 97660,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de La Réunion",
                "city" => "Saint-Denis",
                "code_postal" => 97744,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de la Polynésie Française",
                "city" => "Punaauia",
                "code_postal" => 98702,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],
            [
                "name" => "Université de la Nouvelle-Calédonie",
                "city" => "Nouméa",
                "code_postal" => 98851,
                "created_at"=>$now,
                "updated_at"=>$now,
            ],

        );
    }
}
